// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyANPiBSp88mirUgLxn0yYEexScm1uCgJcQ",
    authDomain: "webapp-a31ae.firebaseapp.com",
    projectId: "webapp-a31ae",
    storageBucket: "webapp-a31ae.appspot.com",
    messagingSenderId: "529367101886",
    appId: "1:529367101886:web:8b6eb7164a47ff660bc9ef",
    measurementId: "G-GLXQZLSNLG",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSehJ9BzTvIvGmG3VXvXj3OdXdWHyO4Vo',
    appId: '1:311253839965:android:e27d85da19358973d29db4',
    messagingSenderId: '311253839965',
    projectId: 'tets-my-online-doctor',
    storageBucket: 'tets-my-online-doctor.appspot.com',
  );
}
